---
- hosts: linux04
  become: true
  tasks:
  - name: instalamos apache
    package:
      name: httpd
      state: present
    tags: install
  - name: iniciamos httpd y lo dejamos persistente en el reboot
    service:
      name: httpd
      state: started
      enabled: yes
    tags: config
  - name: creamos pagina de bienvenida
    copy:
      dest: /var/www/html/index.html
      content: |
        <html>
        <body>
        <h1>It works!</h1>
        Que bonito!
        Que bueno!
        Que bueno"
        </body>
        </html>
    tags: config