---
- hosts: "{{ servidores }}"
  gather_facts: false
  tasks:
  - name: validamos conexion web
    uri:
      url: "http://localhost"
    ignore_errors: true
  - name: Continua siguiente tarea
    debug:
      msg: "Hola que tal? te funcionó el ejercicio?"
    