---
- hosts: "{{ servidores }}"
  become: true
  tasks:
  - name: crear usuario
    user:
      name: "{{ item.empleado }}"
      groups: "{{ item.equipo }}"
      shell: "/bin/bash"
      comment: "usuario creado por ansible"
      state: present
    with_items: "{{ usuarios }}"